
"use client";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import {
  Calculator,
  Leaf,
  Atom,
  FlaskConical,
  Loader2,
  AlertTriangle,
  Image as ImageIcon,
} from "lucide-react";
import type { GenerateIgcseQuestionsOutput } from "@/ai/flows/generate-igcse-questions";

type QuestionDisplayProps = {
  questions: GenerateIgcseQuestionsOutput['questions'] | null;
  isLoading: boolean;
  error: string | null;
};

const WelcomeScreen = () => (
  <div className="flex flex-1 items-center justify-center">
    <Card className="w-full max-w-2xl text-center">
      <CardHeader>
        <CardTitle className="font-headline text-3xl">
          Welcome to the IGCSE Gemini Generator
        </CardTitle>
        <CardDescription>
          Select a subject and question type in the sidebar to get started.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex justify-center gap-8 text-muted-foreground">
        <div className="flex flex-col items-center gap-2">
          <Calculator className="size-8" />
          <span>Math</span>
        </div>
        <div className="flex flex-col items-center gap-2">
          <Leaf className="size-8" />
          <span>Biology</span>
        </div>
        <div className="flex flex-col items-center gap-2">
          <Atom className="size-8" />
          <span>Physics</span>
        </div>
        <div className="flex flex-col items-center gap-2">
          <FlaskConical className="size-8" />
          <span>Chemistry</span>
        </div>
      </CardContent>
    </Card>
  </div>
);

const LoadingSpinner = () => (
  <div className="flex flex-1 flex-col items-center justify-center gap-4">
    <Loader2 className="size-12 animate-spin text-primary" />
    <p className="text-lg text-muted-foreground">Generating questions...</p>
  </div>
);

const ErrorDisplay = ({ error }: { error: string }) => (
  <div className="flex flex-1 items-center justify-center">
    <Alert variant="destructive" className="max-w-md">
      <AlertTriangle className="h-4 w-4" />
      <AlertTitle>Error</AlertTitle>
      <AlertDescription>{error}</AlertDescription>
    </Alert>
  </div>
);

export function QuestionDisplay({
  questions,
  isLoading,
  error,
}: QuestionDisplayProps) {
  if (isLoading) {
    return <LoadingSpinner />;
  }

  if (error) {
    return <ErrorDisplay error={error} />;
  }

  if (questions) {
    return (
      <div className="container mx-auto max-w-4xl py-8">
        <Card>
          <CardHeader>
            <CardTitle className="font-headline">Generated Questions</CardTitle>
            <CardDescription>
              Here are the questions generated by the AI.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {questions.map((q, index) => (
              <div key={index} className="rounded-md border bg-secondary/50 p-4">
                <p className="font-code whitespace-pre-wrap text-sm text-secondary-foreground">
                  {q.questionText}
                </p>
                {q.diagramDescription && q.diagramDescription.toLowerCase() !== 'null' && (
                   <Card className="mt-4">
                     <CardHeader className="flex flex-row items-center gap-2 space-y-0 pb-2">
                       <ImageIcon className="size-4 text-muted-foreground" />
                       <CardTitle className="text-sm font-medium">Diagram Description</CardTitle>
                     </CardHeader>
                     <CardContent>
                       <p className="text-sm text-muted-foreground">{q.diagramDescription}</p>
                     </CardContent>
                   </Card>
                )}
              </div>
            ))}
          </CardContent>
        </Card>
      </div>
    );
  }

  return <WelcomeScreen />;
}

    